# Generated by Django 2.0.2 on 2019-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='courseno',
            field=models.TextField(default='', null='true'),
        ),
        migrations.AlterField(
            model_name='form',
            name='credit',
            field=models.TextField(default='', null='true'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.TextField(default='', null='true'),
        ),
    ]
