# Generated by Django 2.0.2 on 2019-09-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=255, null='true')),
                ('Email', models.CharField(max_length=255, null='true')),
                ('Session', models.CharField(max_length=255, null='true')),
                ('Department', models.CharField(max_length=255, null='true')),
            ],
        ),
    ]
