# Generated by Django 2.0.2 on 2019-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
