# Generated by Django 2.0.2 on 2019-10-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191009_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Session',
        ),
    ]
